# Generated by Django 3.2.18 on 2023-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acccountdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
