# Generated by Django 3.2.18 on 2023-03-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_auto_20230311_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='accounts',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='branch',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='district',
            new_name='country',
        ),
    ]
