# Generated by Django 3.2.18 on 2023-03-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0004_auto_20230318_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
